### ISSUE TITLE
제작 요청 관련 코드를 정리한다

### ISSUE THREAD

**Issue by EomYoosang** [Jandy-SeoulTech/Design-Seller-Back#24]
## Description
제작 요청 관련 코드를 정리한다. 

## Todo
- [x] Request 관련 DTO 재정의
- [x] Request, RequestProduction, ProductionOption 엔티티 재정의 및 각각 관계 재설정
- [x] Request Repository 수정
