### ISSUE TITLE
제작 의뢰 엔티티에 정보를 추가한다

### ISSUE THREAD

**Issue by EomYoosang** [Jandy-SeoulTech/Design-Seller-Back#26]
## Description
제작 의뢰 엔티티에 정보를 추가한다.

## Todo
- [x] 주문일, 배송지, 주문상태 정보를 추가한다.
- [x] 주문자 정보를 추가한다.
- [x] 정보 추가에 따른 비지니스 로직을 수정한다.
